// @flow
export type ResponseContextList[AddressResponse] = {msg: string,code: string,data: Array<AddressResponse>}
export type AddressResponse = {Id: number,name: string,contactPhone: string,addressName: string,phone: string,province: NamedItem,city: NamedItem,district: NamedItem,detail: string,isDefault: boolean}
export type NamedItem = {code: string,name: string}
export type AddressCreateRequest = {name: string,contactPhone: string,addressName: string,phone: string,provinceCode: string,cityCode: string,districtCode: string,detail: string,isDefault: boolean}
export type ResponseContextObject = {msg: string,code: string,data: Object}
export type AddressUpdateRequest = {id: number,name: string,phone: string,contactPhone: string,addressName: string,provinceCode: string,cityCode: string,districtCode: number,detail: string,isDefault: boolean}
export type ResponseContextInt32 = {msg: string,code: string,data: number}
export type ResponseContextList[SysAddressResponse] = {msg: string,code: string,data: Array<SysAddressResponse>}
export type SysAddressResponse = {code: string,parentCode: string,Name: string,FirstLetter: string,PinyinSimple: string,PinyinFull: string,Level: number,Longitude: number,Latitude: number,IsMunicipality: boolean}
export type BannerRequest = {Type: number,PageTypeKey: number,PositionKey: number,DisplayCategoryId: string,FeatureMuseumId: number}
export type ResponseContextList[BannerResponse] = {msg: string,code: string,data: Array<BannerResponse>}
export type BannerResponse = {id: number,platform: number,title: string,type: number,pageTypeId: number,positionId: number,sort: number,module: string,imgs: string,width: number,height: number,beginTime: string,endTime: string,enabled: boolean,pageTypeName: string,positionName: string,typeName: string,platformName: string,LinkUrl: string}
export type ResponseContextQueryCartResponse = {msg: string,code: string,data: QueryCartResponse}
export type QueryCartResponse = {CartList: Array<CartResponse>,TotalPrice: number,DiscountTotalAmount: number,PromotionList: Array<PromotionCarResponse>}
export type CartResponse = {goodsId: number,goodsImage: string,goodsName: string,computedPrice: number,goodsOriginalPrice: number,goodsLimit: number,minLimit: number,increment: number,goodsQuantity: number,goodsStatus: number,introduction: string,isDeleted: boolean,Tag: number,RemainingTime: number,AppDecription: string,PriceChangeRemark: string,QuantityChangeRemark: number}
export type PromotionCarResponse = {PromotionId: number,PrmotionName: string,PromotionType: number,RuleId: number,RuleType: number,DiscountAmount: number,IsApplyed: boolean,PromotionItemResponse: Array<CartResponse>}
export type AddCartRequest = {goodsId: number,quantity: number}
export type SubtractCartRequest = {goodsId: number,quantity: number}
export type MergeCartRequest = {goodsId: number,quantity: number}
export type QueryPageRequestObject = {paging: PageRequest,sort: Array<SortOpt>,condition: Object}
export type PageRequest = {pageSize: number,pageIndex: number}
export type SortOpt = {field: number,isDesc: boolean}
export type ResponseContextPagingResponse[List[NewsSearchResponse]] = {msg: string,code: string,data: PagingResponse[List[NewsSearchResponse]]}
export type PagingResponseList[NewsSearchResponse] = {paging: PageResponse,itemList: Array<array>}
export type PageResponse = {total: number,currentPage: number,pageSize: number,pageCount: number}
export type NewsSearchResponse = {title: string,content: string,type: number,sort: number,enabled: boolean,startTime: string,endTime: string,createUser: number}
export type ResponseContextNewsResponse = {msg: string,code: string,data: NewsResponse}
export type NewsResponse = {title: string,content: string,type: number,sort: number,enabled: boolean,startTime: string,endTime: string}
export type ResponseContextPageTypeResponse = {msg: string,code: string,data: PageTypeResponse}
export type PageTypeResponse = {id: number,name: string}
export type PostTopicSearchRequest = {IsMenu: boolean}
export type ResponseContextTopicPostTopicSearchResponse = {msg: string,code: string,data: TopicPostTopicSearchResponse}
export type TopicPostTopicSearchResponse = {Id: number,IsMenu: boolean,Title: string,Url: string}
export type PostTopicUrlSearchRequest = {Url: string}
export type ResponseContextTopicResponse = {msg: string,code: string,data: TopicResponse}
export type TopicResponse = {Id: number,Title: string,ShortTitle: string,IsMenu: boolean,Sort: number,Url: string,Content: string,Enabled: boolean,StartTime: string,EndTime: string}
export type ResponseContextString = {msg: string,code: string,data: string}
export type ResponseContextImgCapcha = {msg: string,code: string,data: ImgCapcha}
export type ImgCapcha = {session: string,img: string}
export type FloorRequest = {pageTypeKey: number,displayCategoryId: number,featureMuseumId: number}
export type ResponseContextList[PageFloorDetail] = {msg: string,code: string,data: Array<PageFloorDetail>}
export type PageFloorDetail = {title: string,pageTemplate: string,sort: number,tags: Array<PageFloorTagDetail>}
export type PageFloorTagDetail = {name: string,sort: number,advertisements: Array<PageFloorTagAdvertisementDetail>,goods: Array<PageFloorTagGoodsDetail>,txtLinks: Array<PageFloorTagTxtLinksDetail>}
export type PageFloorTagAdvertisementDetail = {title: string,type: number,imgs: string,linkUrl: string,sort: number}
export type PageFloorTagGoodsDetail = {goodsId: number,goodsName: string,goodsSn: string,imageCover: string,sort: number,marketPrice: number,salePrice: number,computedPrice: number,phonePrice: number,introduction: string,isPresale: boolean,status: number,stock: number,presaleTime: string,IsTraceSource: boolean}
export type PageFloorTagTxtLinksDetail = {name: string,linkUrl: string,sort: number}
export type ResponseContextList[AddressTreeResponse] = {msg: string,code: string,data: Array<AddressTreeResponse>}
export type AddressTreeResponse = {Code: string,Name: string,PinyinSimple: string,PinyinFull: string,SubRegionList: Array<AddressTreeResponse>}
export type QueryPageRequestFeatureCityAdPostRequest = {paging: PageRequest,sort: Array<SortOpt>,condition: FeatureCityAdPostRequest}
export type FeatureCityAdPostRequest = {PageType: number,PagePostion: number}
export type ResponseContextPagingResponse[FeaturedCityResponse] = {msg: string,code: string,data: PagingResponse[FeaturedCityResponse]}
export type PagingResponseFeaturedCityResponse = {paging: PageResponse,itemList: Array<FeaturedCityResponse>}
export type FeaturedCityResponse = {total: number,images: Array<Image>}
export type Image = {path: string,moduleType: string,moduleId: string,isJumbotron: string}
export type FeatureCityGoodsPostRequest = {GoodsId: number,PlatformType: number,PageTypeId: number,PagePositionId: number,Enable: boolean,StartStartTime: string,StartEndTime: string,EndStartTime: string,EndEndTime: string}
export type ResponseContextIEnumerable[FCGoods] = {msg: string,code: string,data: Array<FCGoods>}
export type FCGoods = {goodsId: number,goodsImage: string,goodsName: string,tag: string,description: string,goodsPrice: number,goodsPriceOriginal: number,stock: number,spec: string,priceUnit: string,shippingFreeLimit: number}
export type FeedbackInput = {Content: string,Phone: string,Platform: number}
export type QueryPageRequestGoodsSearchRequest = {paging: PageRequest,sort: Array<SortOpt>,condition: GoodsSearchRequest}
export type GoodsSearchRequest = {categoryCode: string,keyword: string,brandIds: Array<integer>,minPrice: number,maxPrice: number,salesAreaCodes: Array<string>,weights: Array<number>}
export type ResponseContextPagingResponse[GoodPostGoodsResponse] = {msg: string,code: string,data: PagingResponse[GoodPostGoodsResponse]}
export type PagingResponseGoodPostGoodsResponse = {paging: PageResponse,itemList: Array<GoodPostGoodsResponse>}
export type GoodPostGoodsResponse = {id: number,name: string,keywords: string,categoryCode: string,introduction: string,imagesCarousel: Array<string>,imageCover: string,unit: string,marketPrice: number,salePrice: number,phonePrice: number,stock: number,isTraceSource: boolean,isPresale: boolean,presaleTime: string}
export type ResponseContextGoodsLevelResponse = {msg: string,code: string,data: GoodsLevelResponse}
export type GoodsLevelResponse = {categories: Array<GoodsLevel>}
export type GoodsLevel = {name: string,code: string,icon: string}
export type AddGoodsToFavoriteRequest = {GoodsIds: Array<integer>}
export type ResponseContextGoodsIsStored = {msg: string,code: string,data: GoodsIsStored}
export type GoodsIsStored = {isCollected: boolean}
export type ResponseContextGoodsInfoBasic = {msg: string,code: string,data: GoodsInfoBasic}
export type GoodsInfoBasic = {id: number,name: string,categoryCode: string,description: string,introduction: string,increment: number,maxLimit: number,minLimit: number,imagesCarousel: Array<string>,imageCover: string,unit: string,marketPrice: number,salePrice: number,phonePrice: number,stock: number,packageList: string,notice: string,isTraceSource: boolean,isPresale: boolean,presaleTime: string,promotion: FlashSaleViewModel,properties: Array<GeneralAttributes>,originDistrictCode: string}
export type FlashSaleViewModel = {id: number,goodsId: number,price: number,obligateStock: number,limitCount: number,img: string,beginTime: string,endTime: string,remark: string,status: number}
export type GeneralAttributes = {name: string,value: string}
export type ResponseContextHotSearchKeysResponse = {msg: string,code: string,data: HotSearchKeysResponse}
export type HotSearchKeysResponse = {recommendList: Array<string>}
export type ResponseContextCategory = {msg: string,code: string,data: Category}
export type Category = {name: string,code: string,icon: string,subCategories: Array<Category>}
export type QueryPageRequestBannerSearchRequest = {paging: PageRequest,sort: Array<SortOpt>,condition: BannerSearchRequest}
export type BannerSearchRequest = {Type: number,PageTypeKey: number,PositionKey: number,DisplayCategoryId: string,FeatureMuseumId: number}
export type ResponseContextGoodOriginResponseDTO[GoodGetGoodsOriginResponse] = {msg: string,code: string,data: GoodOriginResponseDTO[GoodGetGoodsOriginResponse]}
export type GoodOriginResponseDTOGoodGetGoodsOriginResponse = {banner: Array<OriginAdvertisemenResponse>,paging: PageResponse,itemList: Array<GoodGetGoodsOriginResponse>}
export type OriginAdvertisemenResponse = {Title: string,Type: string,LinkUrl: string,Module: string,Imgs: string}
export type GoodGetGoodsOriginResponse = {Id: number,GoodsSn: string,Name: string,CategoryCode: string,Brand: number,ImageCover: string,Status: number,Keywords: string,Type: number,Description: string,Introduction: string,MarketPrice: number,SalePrice: number,PhonePrice: number,MaxLimit: number,MinLimit: number,IsTraceSource: boolean,AvailableStock: number,SalesVolume: number,ComputedPrice: number,isPresale: boolean,presaleTime: string}
export type ResponseContextNewGoodsDto = {msg: string,code: string,data: NewGoodsDto}
export type NewGoodsDto = {AdvertisemenItem: Array<AdvertisemenSearchResponse>,itemList: PagingResponse[GoodsRecommendSearchResponse]}
export type AdvertisemenSearchResponse = {Title: string,Type: string,LinkUrl: string,Module: string}
export type PagingResponseGoodsRecommendSearchResponse = {paging: PageResponse,itemList: Array<GoodsRecommendSearchResponse>}
export type GoodsRecommendSearchResponse = {Id: number,goodsId: number,GoodName: string,goodsImage: string,desc: string,goodsPrice: number,goodsPriceOriginal: number,priceUnit: number}
export type QueryPageRequestPageTypeToPostionListRequest = {paging: PageRequest,sort: Array<SortOpt>,condition: PageTypeToPostionListRequest}
export type PageTypeToPostionListRequest = {pageTypeKey: number,positionKey: number,DisplayCategoryId: string,FeatureMuseumId: number}
export type ResponseContextShoppingRecommendSearchDTO = {msg: string,code: string,data: ShoppingRecommendSearchDTO}
export type ShoppingRecommendSearchDTO = {paging: PageResponse,itemList: Array<ShoppingRecommendSearchResponse>}
export type ShoppingRecommendSearchResponse = {id: number,goodsId: number,goodsName: string,goodsImage: string,desc: string,marketPrice: number,salePrice: number,phonePrice: number,priceUnit: number,computedPrice: number,satus: number,availableStock: number,introduction: string,isTraceSource: boolean,isPresale: boolean,presaleTime: string}
export type ResponseContextGoodsCategoryAncestorsResponse = {msg: string,code: string,data: GoodsCategoryAncestorsResponse}
export type GoodsCategoryAncestorsResponse = {Name: string,Code: string,Icon: string}
export type ResponseContextList[GoodPostGoodsResponse] = {msg: string,code: string,data: Array<GoodPostGoodsResponse>}
export type ResponseContextGoodsSearchResponse = {msg: string,code: string,data: GoodsSearchResponse}
export type GoodsSearchResponse = {brands: Array<BrandDto>,priceBounds: Array<string>,salesAreas: Array<SalesAreaDto>,weights: Array<number>}
export type BrandDto = {id: number,name: string}
export type SalesAreaDto = {code: string,name: string}
export type FreightRuleRequest = {GoodsId: number,ProvinceCode: string,CityCode: string}
export type ResponseContextList[String] = {msg: string,code: string,data: Array<string>}
export type ResponseContextList[HelpCenterResponse] = {msg: string,code: string,data: Array<HelpCenterResponse>}
export type HelpCenterResponse = {title: string,content: string}
export type ResponseContextIEnumerable[CategoryAndTitle] = {msg: string,code: string,data: Array<CategoryAndTitle>}
export type CategoryAndTitle = {id: number,name: string,pages: Array<HelpCenterShort>}
export type HelpCenterShort = {id: number,title: string,sort: number,isShowFooter: boolean}
export type ResponseContextHelpCenterDto = {msg: string,code: string,data: HelpCenterDto}
export type HelpCenterDto = {Id: number,title: string,content: string,categoryId: number,categoryName: string,isShowFooter: boolean,sort: number,enabled: boolean,platform: number}
export type KeyWordSearchRequest = {PageTypeKey: number,DisplayCategoryCode: string,FeatureMuseumId: number}
export type ResponseContextList[KeyWordSearchResponse] = {msg: string,code: string,data: Array<KeyWordSearchResponse>}
export type KeyWordSearchResponse = {Id: number,KeyWord: string}
export type ResponseContextList[HotKeyWordSearchResponse] = {msg: string,code: string,data: Array<HotKeyWordSearchResponse>}
export type HotKeyWordSearchResponse = {Id: number,KeyWord: string}
export type ResponseContextList[KeyWordSearchRequest] = {msg: string,code: string,data: Array<KeyWordSearchRequest>}
export type SensitiveSearchRequest = {KeyWords: string}
export type ResponseContextBoolean = {msg: string,code: string,data: boolean}
export type ResponseContextMuseumDetailResponse = {msg: string,code: string,data: MuseumDetailResponse}
export type MuseumDetailResponse = {id: number,name: string,provinceCode: string,cityCode: string,districtCode: string,promotionTitle: string,isHotMuseum: boolean,logoUrl: string,coverUrl: Array<string>,enabled: boolean,sort: number,introduction: string}
export type ResponseContextPagingResponse[Goods] = {msg: string,code: string,data: PagingResponse[Goods]}
export type PagingResponseGoods = {paging: PageResponse,itemList: Array<Goods>}
export type Goods = {ImageCover: string,Name: string,Introduction: string,OriginProvinceCode: string,OriginCityCode: string,OriginDistrictCode: string,IsTraceSource: boolean,UnitValue: string,MarketPrice: number,SalePrice: number,PhonePrice: number}
export type ResponseContextPagingResponse[Museum] = {msg: string,code: string,data: PagingResponse[Museum]}
export type PagingResponseMuseum = {paging: PageResponse,itemList: Array<Museum>}
export type Museum = {id: number,sort: number,title: string,imageURL: string,promotionTitle: string,introduction: string,tags: Array<Tag>}
export type Tag = {name: string,linkUrl: string}
export type ResponseContextPagingResponse[MuseumDetailResponse] = {msg: string,code: string,data: PagingResponse[MuseumDetailResponse]}
export type PagingResponseMuseumDetailResponse = {paging: PageResponse,itemList: Array<MuseumDetailResponse>}
export type ResponseContextPagingResponse[OrderAppInfo] = {msg: string,code: string,data: PagingResponse[OrderAppInfo]}
export type PagingResponseOrderAppInfo = {paging: PageResponse,itemList: Array<OrderAppInfo>}
export type OrderAppInfo = {Id: number,Sn: string,TotalPrice: number,Freight: number,CreateTime: string,order: Array<OrderGetOrdersResponse>}
export type OrderGetOrdersResponse = {OrderId: number,Sn: string,OrderGroup: string,OrderStatus: number,OrderTotalPrice: number,Freight: number,GoodsLists: Array<GoodsInfoOutput>}
export type GoodsInfoOutput = {quatity: number,goodsid: number,goodsImage: string,goodsName: string,desc: string,goodsPrice: number,goodsPriceOriginal: number,totalPrice: number}
export type CheckoutCartRequest = {goods: Array<GoodsRequest>,platformType: number}
export type GoodsRequest = {goodsId: number,goodsQuantity: number,IsActivity: boolean}
export type ResponseContextCheckoutCartResponse = {msg: string,code: string,data: CheckoutCartResponse}
export type CheckoutCartResponse = {shippingFee: number,goodsTotalCount: number,goodsTotalPrice: number,DiscountTotalAmount: number,Address: Array<AddressGetAddressResponse>,Goods: Array<GoodsResponse>,ResultMessage: Array<OrderResultMessage>,CanUseCoupons: Array<OrderCouponResponse>}
export type AddressGetAddressResponse = {id: number,name: string,phone: string,Province: CityData,City: CityData,District: CityData,detail: string,isDefault: boolean}
export type GoodsResponse = {goodsId: number,goodsName: string,desc: string,goodsQuantity: number,salePrice: number,MaxLimit: number,MinLimit: number,ImageCover: string}
export type OrderResultMessage = {MessageType: number,Message: string}
export type OrderCouponResponse = {CouponId: number,CouponName: string,CouponCode: number,FaceValue: number}
export type CityData = {Code: string,Name: string}
export type ResponseContextOrderDetailOutput = {msg: string,code: string,data: OrderDetailOutput}
export type OrderDetailOutput = {Sn: string,CreateTime: string,OrderStatus: string,ShippingFee: number,TotalPrice: number,OrderPayment: number,LogisticsCompany: string,UserMessage: string,InvoiceType: number,InvoiceTitle: string,InvoiceContent: number,order: Array<OrderGetOrdersResponse>,address: Array<OrderGetOrdersDetailResponseAddressInfo>}
export type OrderGetOrdersDetailResponseAddressInfo = {Phone: string,Name: string,Telephone: string,Detail: string,Province: string,City: string,District: string}
export type OrderPostOrdersSubmitRequest = {goodsLists: Array<GoodsRequest>,addressId: number,userMessage: string,platformType: number,receiveInfoName: string,receiveInfoPhone: string,receiveInfoTelephone: string,receiveInfoDetail: string,ProvinceCode: string,CityCode: string,DistrictCode: string,InvoiceType: number,InvoiceTitle: string,InvoiceContent: string,OrderPayment: number,UsedCoupons: Array<OrderCouponRequest>}
export type OrderCouponRequest = {CouponId: number,CouponCode: number}
export type ResponseContextOrderPayOrdersDetailResponse = {msg: string,code: string,data: OrderPayOrdersDetailResponse}
export type OrderPayOrdersDetailResponse = {Sn: string,OrderPayment: number,address: Array<OrderGetOrdersDetailResponseAddressInfo>,GoodsLists: Array<GoodsInfoOutput>,PaymentType: Array<PayTypeResponse>}
export type PayTypeResponse = {id: number,name: string,billType: number,sort: number}
export type PayRequest = {Sn: string,PaymentType: number,ReturnUrl: string,CancelUrl: string}
export type ResponseContextPayResponse = {msg: string,code: string,data: PayResponse}
export type PayResponse = {errCode: number,retMsg: string,merOrder: string,gateSn: string,channelSn: string,channelTnTime: string,txnAmount: string,currency: string,status: string,data: string}
export type ConfirmRequestDTO = {Sn: string,PaymentType: number,Account: string,PassWord: string,Captcha: string,CodeToken: string}
export type ResponseContextPagingResponse[PromotionGoodsInfo] = {msg: string,code: string,data: PagingResponse[PromotionGoodsInfo]}
export type PagingResponsePromotionGoodsInfo = {paging: PageResponse,itemList: Array<PromotionGoodsInfo>}
export type PromotionGoodsInfo = {goodsId: number,GoodsSn: string,goodsImage: string,bannerImages: Array<string>,goodsName: string,desc: string,goodsPrice: number,goodsPriceOriginal: number,marketingPrice: number,priceUnit: string,SalesVolume: number,stock: number,promotion: Array<string>,remainingTime: number,shippingFreeLimit: number,goodsStatus: number,goodsLimit: number}
export type ResponseContextCouponRecevieResponse = {msg: string,code: string,data: CouponRecevieResponse}
export type CouponRecevieResponse = {CouponId: number,CouponName: string,CouponCode: number,FaceValue: number,ReceivingTime: string,UseStartTime: string,UseEndTime: string}
export type ResponseContextPublicWelfareTypeResponse = {msg: string,code: string,data: PublicWelfareTypeResponse}
export type PublicWelfareTypeResponse = {publicWelfareTypeList: Array<PublicWelfareType>}
export type PublicWelfareType = {id: number,name: string,imgUrl: string}
export type ResponseContextPagingResponse[PublicWefareItem] = {msg: string,code: string,data: PagingResponse[PublicWefareItem]}
export type PagingResponsePublicWefareItem = {paging: PageResponse,itemList: Array<PublicWefareItem>}
export type PublicWefareItem = {imgUrl: Array<string>,name: string,tags: Array<string>,description: string,id: number,tel: string}
export type ResponseContextPWDetail = {msg: string,code: string,data: PWDetail}
export type PWDetail = {name: string,tel: string,StartTime: string,EndeTime: string,newsContent: string}
export type SignUpRequest = {phone: string,verficationCode: string,password: string,email: string,userName: string,imgSession: string,imgCode: string}
export type ResponseContextSignUpResponse = {msg: string,code: string,data: SignUpResponse}
export type SignUpResponse = {sessionId: string}
export type SignInRequest = {account: string,password: string,verifyCode: string,loginType: number}
export type ResetPasswordRequest = {phoneNumber: string,verifyCode: string,newPassword: string}
export type ModifyPasswordRequest = {oldPassword: string,newPassword: string}
export type SendVerificationCodeRequest = {phone: string,verificationCodeType: number}
export type ChangePhoneNumberRequest = {newPhoneNumber: string,verifyCode: number}
export type ResponseContextUserInfoResponse = {msg: string,code: string,data: UserInfoResponse}
export type UserInfoResponse = {userName: string,sex: number,birthday: string}
export type UserInfoRequest = {userName: string,sex: number,birthday: string}
export type ResponseContextPagingResponse[CustomerFavoritesResposne] = {msg: string,code: string,data: PagingResponse[CustomerFavoritesResposne]}
export type PagingResponseCustomerFavoritesResposne = {paging: PageResponse,itemList: Array<CustomerFavoritesResposne>}
export type CustomerFavoritesResposne = {id: number,name: string,keywords: string,introduction: string,imageCover: string,unit: string,marketPrice: number,salePrice: number,phonePrice: number,stock: number,isTraceSource: boolean,isPresale: boolean,presaleTime: string}
